---
main_uid: 1000
main_gid: "{{ main_uid }}"
main_tzone: "America/New_York"
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ main_tzone }}"

docker_update_command: >
  docker-compose pull &&
  docker-compose down &&
  docker-compose up --force-recreate -d &&
  docker system prune -af
