---
- hosts: calpamos
  remote_user: "{{ calpamos_user }}"
  vars_files:
    - 'vars/vault.yml'
  vars:
    ansible_become_pass: "{{ calpamos_become_password }}"
  roles:
    - role: base
    - role: calpamos

- hosts: carthonasi
  remote_user: "{{ carthonasi_user }}"
  vars_files:
    - 'vars/vault.yml'
  vars:
    ansible_become_pass: "{{ carthonasi_become_password }}"
  roles:
    - role: base

- hosts: gatekeeper
  remote_user: "{{ gatekeeper_user }}"
  vars_files:
    - 'vars/vault.yml'
  vars:
    ansible_become_pass: "{{ gatekeeper_become_password }}"
  roles:
    - role: base

- hosts: heimdallr
  remote_user: "{{ heimdallr_user }}"
  vars_files:
    - 'vars/vault.yml'
  vars:
    ansible_become_pass: "{{ heimdallr_become_password }}"
  roles:
    - role: base

- hosts: matrix
  remote_user: "{{ matrix_user }}"
  vars_files:
    - 'vars/vault.yml'
  vars:
    ansible_become_pass: "{{ matrix_become_password }}"
  roles:
    - role: base
    - role: matrix
    - role: ironicbadger.ansible_role_docker_compose_generator
      tags: compose
