---
# Update All
- hosts: all
  become: true
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: base
  tags: update

- hosts: carthonasi
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: nfs-client
    #  - role: restic

- hosts: gatekeeper
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: nfs-client
    #  - role: restic

- hosts: matrix
  vars_files:
    - 'vars/vault.yml'
  roles:
    #  - role: restic
    - role: docker
    - role: ytdlp
    #  - role: minecraft

# Deploy docker services on Matrix
- hosts: matrix
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: matrix
    - role: ironicbadger.docker_compose_generator
  tags: docker
