---
# Update All 
- hosts: all
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: base
      tags: update

# Update Docker services
- hosts: docker
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: docker
      tags: docker

# Deploy Docker services on Matrix
- hosts: matrix
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: ironicbadger.ansible_role_docker_compose_generator
      tags: compose
