---
# Update All 
- hosts: all
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: base
      tags: update

# Update Docker services on Calpamos
- hosts: calpamos
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: calpamos

# Update Docker services on Matrix
- hosts: matrix
  vars_files:
    - 'vars/vault.yml'
  roles:
    - role: matrix
    - role: ironicbadger.ansible_role_docker_compose_generator
      tags: compose
