---

- name: update apt cache
  become: true
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 3600

- name: ensure dependencies are installed
  become: true
  ansible.builtin.package:
    name:
      - software-properties-common
      - screen
      - openjdk-17-jdk-headless
      - jq
    state: present

- name: copy minecraft server config templates in place.
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "~/{{ mc_dir }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - 'ops.json'
    - 'server'
    - 'server.properties'
    - 'whitelist.json'

- name: copy minecraft static files in place.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/{{ mc_dir }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - 'banned-ips.json'
    - 'banned-players.json'
    - 'eula.txt'

- name: copy minecraft server administration script in place.
  ansible.builtin.template:
    src: server
    dest: "~/{{ mc_dir }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: a+x

- name: copy systemd service config in place.
  become: true
  ansible.builtin.template:
    src: minecraft.service
    dest: "/etc/systemd/system/"
    owner: "root"
    group: "root"
    mode: 0644

- name: stop minecraft server if it is running
  become: true
  ansible.builtin.service:
    name: minecraft
    state: stopped

- name: start & enable the minecraft service.
  become: true
  ansible.builtin.systemd:
    name: minecraft
    state: started
    daemon_reload: true
    enabled: true

- name: copy server status monitoring cron script in place.
  become: true
  ansible.builtin.template:
    src: "mc-healthcheck.sh"
    dest: "/usr/local/bin/"
    owner: "root"
    group: "root"
    mode: a+x

- name: add server status monitor to crontab.
  ansible.builtin.cron:
    name: minecraft server healthcheck
    job: "/bin/bash /usr/local/bin/mc-healthcheck.sh"
    user: "{{ ansible_user }}"
    minute: "0"
    state: present
