---

- name: create docker configuration directories
  file:
    path: "~/appdata/{{ item }}"
    state: directory
    recurse: true
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0755
  loop:
    - paperless-ng
    - jellyfin
    - mariadb
    - podgrab
    - diun
    - scrutiny
    - freshrss
    - uptime-kuma
