---

- name: create docker configuration directories
  become: true
  file:
    path: "~/appdata/{{ item }}"
    state: directory
    recurse: true
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0755
  loop:
    - diun
    - freshrss
    - gitea
    - homeassistant
    - homer
    - jellyfin
    - mariadb
    - paperless-ng
    - podgrab
    - postgresql
    - scrutiny
    - uptime-kuma

- name: deploy homer assets
  become: true
  copy:
    src: "tools"
    dest: "/home/{{ remote_user }}/appdata/homer/"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0755

- name: copy homer dashboard configuration
  become: true
  template:
    src: "config.yml"
    dest: "/home/{{ remote_user }}/appdata/homer/"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0755
