---

- name: include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: "Check if {{ autorestic_install_path }} exists."
  ansible.builtin.stat:
    path: "{{ autorestic_install_path }}"
  register: is_installed

- name: Set autorestic installation status.
  ansible.builtin.set_fact:
    autorestic_installed: "{{ is_installed.stat.exists }}"

- name: Get autorestic version.
  ansible.builtin.shell: |
    set -o pipefail
    {{ is_installed.stat.path }} --version | \
    grep -oP 'autorestic\ version\ \K[0-9]*\.[0-9]*\.[0-9]*'
  args:
    executable: /bin/bash
  register: installed_version_register
  changed_when: false
  when: autorestic_installed

- name: Query GitHub API for autorestic release info.
  ansible.builtin.uri:
    url: "{{ autorestic_releases_api }}"
    return_content: true
  register: release_version_register

- name: Identify latest version of autorestic.
  ansible.builtin.set_fact:
    autorestic_ver: "{{ release_version_register.json.tag_name|regex_replace('v') }}"

- name: Perform autorestic installation via github source
  block:
    - name: "Ensure {{ autorestic_download_directory }} does not exist."
      ansible.builtin.file:
        path: "{{ autorestic_download_directory }}"
        state: absent

    - name: "Create {{ autorestic_download_directory }}."
      ansible.builtin.file:
        path: "{{ autorestic_download_directory }}"
        state: directory
        mode: 0755

    - name: Download autorestic.
      ansible.builtin.get_url:
        url: "{{ autorestic_repo_url }}/v{{ autorestic_ver }}/autorestic_{{ autorestic_ver }}_{{ autorestic_distro }}.bz2"
        dest: "{{ autorestic_download_directory }}"
        force: true
        owner: root
        group: root
        mode: +x

    - name: Identify autorestic compressed file.
      ansible.builtin.set_fact: file_name="autorestic_{{ autorestic_ver }}_{{ autorestic_distro }}.bz2"

    - name: Unzip and update autorestic.
      ansible.builtin.shell: |
        set -o pipefail
        cd {{ autorestic_download_directory }} &&
        bzip2 -d {{ file_name }} &&
        mv {{ file_name | regex_replace('.bz2') }} {{ autorestic_install_path }}
      args:
        executable: /bin/bash

  when: not autorestic_installed or (autorestic_installed and installed_version_register.stdout != autorestic_ver)
