---

- name: Update apt cache
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure dependencies are installed
  ansible.builtin.package:
    name:
      - python3
      - ffmpeg
    state: present
