---

- name: "Install pre-requisites."
  include_tasks: install-prereqs.yml
  vars:
    ansible_become: true

- name: "Deploy yt-dlp."
  include_tasks: install-yt-dlp.yml
  vars:
    ansible_become: true

- name: "Configure yt-dlp."
  include_tasks: configure-yt-dlp.yml
  vars:
    ansible_become: true
