---

- name: "Install pre-requisites."
  become: true
  include_tasks: install-prereqs.yml

- name: "Deploy yt-dlp."
  become: true
  include_tasks: install-yt-dlp.yml

- name: "Configure yt-dlp."
  become: true
  include_tasks: configure-yt-dlp.yml
