---

remote_user: "{{ calpamos_user }}"
ansible_become_pass: "{{ calpamos_become_password }}"

docker_users:
  - "{{ calpamos_user }}"

appdata_path: "/home/{{ calpamos_user }}/appdata"
containers:
  - service_name: homeassistant
    container_name: homeassistant
    image: ghcr.io/home-assistant/raspberrypi4-homeassistant:stable
    active: true
    include_global_env_vars: true
    volumes:
      - "{{ appdata_path }}/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    privileged: true
    network_mode: host
  ###
  - service_name: homer
    container_name: homer
    image: b4bz/homer
    active: true
    include_global_env_vars: true
    volumes:
      - "{{ appdata_path }}/homer:/www/assets"
    ports:
      - "{{ secret_homer_port }}:{{ secret_homer_port }}"
    restart: unless-stopped
  ###
  - service_name: diun
    container_name: diun
    image: crazymax/diun:latest
    active: true
    command:
      - serve
    volumes:
      - "{{ appdata_path }}/diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - "{{ secret_diun_notification_handler }}"
      - "{{ secret_diun_notification_message }}"
    restart: unless-stopped
  ###
  - service_name: gitea
    container_name: gitea
    image: kunde21/gitea-arm:latest
    active: true
    include_global_env_vars: true
    environment: "{{ secret_gitea_db_config }}"
    networks:
      - gitea
    volumes:
      - "{{ appdata_path }}/gitea:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports: "{{ secret_gitea_ports }}"
    depends_on:
      - db
    restart: always
  ###
  - service_name: db
    container_name: db
    image: postgres:latest
    active: true
    include_global_env_vars: true
    environment: "{{ secret_calpamos_db_config }}"
    volumes:
      - "{{ appdata_path }}/postgresql/initdb.d:/docker-entrypoint-initdb.d"
      - "{{ appdata_path }}/postgresql/data:/var/lib/postgresql/data"
      - "{{ appdata_path }}/postgresql/postgres.conf:/etc/postgresql/postgresql.conf"
    networks:
      - gitea
    restart: always
  ###
  - service_name: adminer
    container_name: adminer
    image: adminer
    active: true
    networks:
      - gitea
    ports:
      - "{{ secret_adminer_ports }}"
    restart: always
networks:
  gitea:
    external: false
