---

- name: update apt cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags: update

- name: update all packages
  become: true
  apt:
    upgrade: 'full'
    autoremove: true
  tags: update
