---

- name: update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: update all packages
  become: true
  ansible.builtin.apt:
    upgrade: 'full'
    autoremove: true

- name: check for presence of reboot-required file
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: need_to_reboot

- name: reboot if required
  become: true
  ansible.builtin.reboot:
  when: need_to_reboot.stat.exists
