---

name: Run Linters

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansiblelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        with:
          targets: "./run.yml"
          path: "./.config/ansible-lint.yml"
          override-deps: |
            rich>=9.5.1,<11.0.0

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.'
          yamllint_config_filepath: './.config/yamllint.yml'
          yamllint_strict: false
          yamllint_comment: true
