---

- name: create docker configuration directories
  file:
    path: "~/appdata/{{ item }}"
    state: directory
    recurse: true
  loop:
    - homeassistant
    - homer
    - diun
    - gitea
    - postgresql

- name: deploy homer assets
  become: true
  copy:
    src: "tools"
    dest: "/home/{{ remote_user }}/appdata/homer/"

- name: copy homer dashboard configuration
  become: true
  template:
    src: "config.yml"
    dest: "/home/{{ remote_user }}/appdata/homer/"
